version: '3'

services:
  My_db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres_async
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./data_async:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  My_db_django:
    image: postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: postgres_django
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./data_django:/var/lib/postgresql/data 

volumes:
  redis_data:
  data_async:
  data_django:
