# Generated by Django 5.0.6 on 2024-05-22 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoteapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autors',
            name='born_date',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='autors',
            name='born_location',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='autors',
            name='description',
            field=models.CharField(max_length=2500),
        ),
        migrations.AlterField(
            model_name='autors',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
