# Generated by Django 5.0.6 on 2024-05-22 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoteapp', '0003_alter_autors_description_alter_quotes_quote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autors',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='quote',
            field=models.TextField(),
        ),
    ]
